### ISSUE TITLE
Solution walkthroughs?

### ISSUE THREAD

**Issue by rijobro** [wrongbaud/hackaday-u#3]
I see the source code is available for the exercises, it would be great if there were walkthroughs for them too. I know that would require some time but it would be a good stepping stone to use before resorting to looking at the source code.

Either way, cheers for the material!

**Comment by rijobro** [comment]
For example, in the `variables-example` of session two, how do I know that `XorMe` is of type `int64_t`? 

Further, when I set it to be `int64_t` (right click, Data, Choose Data Type...,), it's display value doesn't change. In my Listing window, it shows up as `DEADBEEFFACECAFEh`, whereas in your source code, the value is `0xDEADBEEFFACECAFE`. I'm not sure how I would be able solve this without the source code.

**Comment by wrongbaud** [comment]
Those two values are the same, Ghidra appends the ```h``` character to hexadecimal numbers. In order to determine the size of that variable (assuming that you didn't know it was a 64-bit integer) you can examine how the loop interacts with it and goes beyond the values that could be used by a 32-bit int.

**Comment by wrongbaud** [comment]
Also to answer the original question - right now I don't have fully written walkthroughs for each challenge. The original hope was that folks would solve them and issue pull requests with their own walkthroughs - largely because everyone approaches RE differently and it's interesting to see how others tackle challenges like this. If I get the time to put some walkthroughs together I will add them, but right now it's not a big priority for me, and I have a few other projects that have to take precedence.  If you have issues with specific exercises you can either open an issue here and I'll do my best to help - or reach out on twitter.
